version: "3"
services:
  be-server:
    container_name: go-back-end
    restart: always
    build: ./Backend
    ports:
       - "8080:8080"
  client:
    container_name: react-client
    restart: always
    build: ./frontEnd
    environment:
       - REACT_APP_API_URL=docker.for.mac.localhost:8080
    ports:
       - "3000:3000"
    links:
       - be-server
